development:
  clients:
    default:
      database: mongodb_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: mongodb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
        
production:
    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          safe: true